package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with id = 'GitRoot_36'
accordingly, and delete the patch script.
*/
changeVcsRoot(RelativeId("GitRoot_36")) {
    val expected = GitVcsRoot({
        id("GitRoot_36")
        name = "Git Root #36"
        url = "https://github.com/ChubatovaTiger/manyBranches"
        branch = "refs/heads/br-demo36"
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        authMethod = password {
            userName = "ChubatovaTiger"
            password = "credentialsJSON:e6f46e03-5155-46f5-b9ce-8b510ab63ae1"
        }
    }

}
